name: OxygenSystem
version: '${project.version}'
main: cn.goldenpotato.oxygensystem.OxygenSystem
api-version: 1.14
softdepend:
  - PlaceholderAPI
  - ItemsAdder
commands:
  oxygen:
    description: "OxygenSystem"
    aliases: [ox]
    usage: "/oxygen"
